name: "Greet User Action"
description: "Une action qui salue un utilisateur avec un message personnalisé"
inputs:
  message:
    description: "Le message à afficher"
    required: true
outputs:
  message:
    description: "Le message généré par l'action"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.message }}